// <auto-generated />
namespace Ad_Insights_DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addViewModel6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addViewModel6));
        
        string IMigrationMetadata.Id
        {
            get { return "201808290927118_addViewModel6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
